title: Thy Bui # your name (or website title) here
logo: https://avatars.githubusercontent.com/u/108997083?s=200&u=901dc50111eeee9feff89f79f6566b51f13ff4f7&v=4 # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Engineer/Analytics Engineer 
  <br><br>
  A goal-driven data nerd with main focus in data engineer/data manipulation 
  <br><br>
  <a href="https://www.linkedin.com/in/buianthy1412/">LinkedIn</a>
  <a href="https://www.linkedin.com/in/buianthy1412/overlay/1635517328323/single-media-viewer/?profileId=ACoAABidDwsBI_rwGJjZmx-oGhxWyMdsOdbHDrI>Resume</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
